# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFNFkpRKEowC87Vmru6stnPjmakqEXEa
"""

!pip install PyPDF2

import requests
import json
import PyPDF2
from google.colab import files

# 🔑 Set your EdenAI API key
EDENAI_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzQ4MWNmZDUtNTRhZC00ZDhhLWJkY2MtM2E3NDViNThlMmEyIiwidHlwZSI6ImFwaV90b2tlbiJ9.dmulKbTbSYj3zXKfXQBC10e7zfcgFzOs3jFRqorXcjw"  # Replace with your API key

# 📂 Upload PDF manually in Colab
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]  # Get uploaded file name

# 📌 Function to extract text from PDF
def extract_text_from_pdf(pdf_path):
    text = ""
    with open(pdf_path, "rb") as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            extracted_text = page.extract_text()
            if extracted_text:
                text += extracted_text + "\n"
    return text.strip()

# 🔥 Function to summarize text using EdenAI API
def summarize_text(text, provider="openai", max_sentences=5):
    url = "https://api.edenai.run/v2/text/summarize"

    headers = {
        "Authorization": f"Bearer {EDENAI_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "response_as_dict": True,
        "attributes_as_list": False,
        "show_original_response": False,
        "text": text,
        "providers": provider,  # Choose provider: openai, cohere, google, etc.
        "language": "en",  # Change if needed (e.g., "fr" for French)
        "max_sentences": max_sentences
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code == 200:
        result = response.json()
        return result[provider]["result"]  # Extract summarized text
    else:
        print("Error:", response.text)
        return None

# 🔄 Extract text from the uploaded PDF
pdf_text = extract_text_from_pdf(pdf_path)

# ✨ Summarize using EdenAI
if pdf_text:
    summary = summarize_text(pdf_text)
    if summary:
        # 🖨 Print the summary
        print("\n===== 📄 AI Summary =====\n")
        print(summary)

        # 💾 Save summary to a file
        summary_filename = "summary.txt"
        with open(summary_filename, "w") as f:
            f.write(summary)

        # 📥 Download the summary file
        files.download(summary_filename)
    else:
        print("❌ Failed to get a summary.")
else:
    print("❌ No text extracted from the PDF.")

